spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 0minus0=zerO

logging:
  level:
  # SQL文をコンソールに出力
   '[com.example.demo.mapper]': debug
   
#mybatis-plus:
#  configuration:
#  global-config:
#    db-config:
#      logicDeleteField: deleted